### PR TITLE
Small set with 2 associated domains

### PR DESCRIPTION
**Pull request by dmarti**
This is a test of First-Party Sets, including one manager domain and two co-branded content sites.

### CODE REVIEW

**Comment by sjledoux** [comment]
Hello, it appears that your submission is failing the PR-Actions due to "https://cardsayings.net", and "https://nourishingpursuits.com" not having accessible .well-known pages. Currently, "https://cafemedia.com" is failing this check as well, likely due to a security feature on your site that blocks https requests made using urllib. That issue should be fixed from a push we just made to main on our end, so you will need to sync your PR with the base branch before that check passes.

**Comment by dmarti** [comment]
@sjledoux Thank you, I have checked the member.json files for both member domains and they both seem to be up.

https://cardsayings.net/.well-known/first-party-set/member.json

https://nourishingpursuits.com/.well-known/first-party-set/member.json

**Comment by sjledoux** [comment]
@dmarti Thank you for clarifying that. The issue would then be because we are expecting the member sites' JSON files to be served at /.well-known/first-party-set, **not** at /.well-known/first-party-set/member.json, causing those checks to fail.

**Comment by dmarti** [comment]
Is a specific MIME type required for the JSON files on member sites? Is a redirect allowed?

**Comment by sjledoux** [comment]
@dmarti I don't believe anything in the code requires a particular MIME type, so any should be fine. 
Redirects are allowed.

**Pull request closed without merging**
