### PR TITLE
change yaml to write comments on PRs

### PR DESCRIPTION
**Pull request by sjledoux**
The Github Action should be modified to leave a comment on the PRs summarizing the success/failures on each check so that filers can more easily see the results of the Github action.

### CODE REVIEW

**Comment by Hulmey** [comment]
> The Github Action should be modified to leave a comment on the PRs summarizing the success/failures on each check so that filers can more easily see the results of the Github action.

**Comment by GUDOKER0823M** [comment]
view it on GitHub
<https://github.com/GoogleChrome/first-party-sets/pull/15#issuecomment-1653758762>
ในวันที่ พฤ. 27 ก.ค. 2023 22:40 น. Stephanie ***@***.***>
เขียนว่า:

**Comment by Mika35551** [comment]
> 
> 
> Looks like you've passed all of the checks!
>

**Comment by Mika35551** [comment]
@@johannhof nice

**Comment by Mika35551** [comment]
> > 
> > 
> > Looks like you've passed all of the checks!
> > 
> 
>

**Pull request merged**
