### PR TITLE
first_party_set updated

### PR DESCRIPTION
**Pull request by Prashanttiwari-htmedia**
first_party_set update with my primary and associate url

### CODE REVIEW

**Comment by sjledoux** [comment]
Hello, thank you for your submission. In addition to the  errors noted in the comment above, please remove all of your edits to the `SCHEMA.json` file. Those changes are unnecessary and will cause issues with the process. You only need to make changes to `first_party_sets.JSON`.

**Comment by jameswu0629** [comment]
@Prashanttiwari-htmedia - 
1. Rollback **SCHEMA.json** and don't make any changes.
2. Change your  **primary** from "https://accounts.hindustantimes.com" to "https://hindustantimes.com"
3. Change **associatedSites** from  "https://mintgenie.livemint.com" to "https://livemint.com"
4. Upload the "first-party-set.json" file to both https://livemint.com/.well-known/first-party-set.json and https://hindustantimes.com/.well-known/first-party-set.json, ensuring that they are accessible to the public.

**Comment by George420kush** [comment]
Gf

**Comment by George420kush** [comment]
Gf

**Comment by Prashanttiwari-htmedia** [comment]
All checks are passed. Please review.

**Comment by sjledoux** [comment]
@Prashanttiwari-htmedia Your changes to first_party_sets.JSON look good. Thank you for working with us to make the necessary fixes! However, this PR still makes changes to SCHEMA.json - the current changes you have made would delete the `required` and `dependentRequired` fields of the first party set schema, which would cause significant problems in our process. As such, we cannot merge this branch until all changes to SCHEMA.json have been reverted. 

An easy way to do this would be to call `git checkout origin/main -- SCHEMA.json` on your local branch, save, then commit and push to the remote.

**Review by sjledoux — APPROVED** [review]

**Pull request merged**
